/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

/// CompanyInfoPlanInfoFunctions : Access to functions for this company.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyInfoPlanInfoFunctions {
    #[serde(rename = "archive", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub archive: Option<Option<bool>>,
    #[serde(rename = "cerved", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cerved: Option<Option<bool>>,
    #[serde(rename = "document_attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub document_attachments: Option<Option<bool>>,
    #[serde(rename = "e_invoice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub e_invoice: Option<Option<bool>>,
    #[serde(rename = "genius", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub genius: Option<Option<bool>>,
    #[serde(rename = "mail_tracking", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mail_tracking: Option<Option<bool>>,
    #[serde(rename = "payment_notifications", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_notifications: Option<Option<bool>>,
    #[serde(rename = "paypal", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub paypal: Option<Option<bool>>,
    #[serde(rename = "receipts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub receipts: Option<Option<bool>>,
    #[serde(rename = "recurring", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recurring: Option<Option<bool>>,
    #[serde(rename = "smtp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub smtp: Option<Option<bool>>,
    #[serde(rename = "sofort", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sofort: Option<Option<bool>>,
    #[serde(rename = "stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stock: Option<Option<bool>>,
    #[serde(rename = "subaccounts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subaccounts: Option<Option<bool>>,
    #[serde(rename = "tessera_sanitaria", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tessera_sanitaria: Option<Option<bool>>,
    #[serde(rename = "ts_digital", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ts_digital: Option<Option<bool>>,
    #[serde(rename = "ts_invoice_trading", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ts_invoice_trading: Option<Option<bool>>,
    #[serde(rename = "ts_pay", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ts_pay: Option<Option<bool>>,
}

impl CompanyInfoPlanInfoFunctions {
    /// Access to functions for this company.
    pub fn new() -> CompanyInfoPlanInfoFunctions {
        CompanyInfoPlanInfoFunctions {
            archive: None,
            cerved: None,
            document_attachments: None,
            e_invoice: None,
            genius: None,
            mail_tracking: None,
            payment_notifications: None,
            paypal: None,
            receipts: None,
            recurring: None,
            smtp: None,
            sofort: None,
            stock: None,
            subaccounts: None,
            tessera_sanitaria: None,
            ts_digital: None,
            ts_invoice_trading: None,
            ts_pay: None,
        }
    }
}


