/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.32
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyInfoPlanInfoFunctionsStatus {
    #[serde(rename = "ts_digital", skip_serializing_if = "Option::is_none")]
    pub ts_digital: Option<Box<models::FunctionStatus>>,
    #[serde(rename = "ts_pay", skip_serializing_if = "Option::is_none")]
    pub ts_pay: Option<Box<models::FunctionStatus>>,
}

impl CompanyInfoPlanInfoFunctionsStatus {
    pub fn new() -> CompanyInfoPlanInfoFunctionsStatus {
        CompanyInfoPlanInfoFunctionsStatus {
            ts_digital: None,
            ts_pay: None,
        }
    }
}

