/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DetailedCountry {
    /// Country name
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// Country settings name
    #[serde(rename = "settings_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub settings_name: Option<Option<String>>,
    /// Country iso code
    #[serde(rename = "iso", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub iso: Option<Option<String>>,
    /// Country fiscal iso code
    #[serde(rename = "fiscal_iso", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fiscal_iso: Option<Option<String>>,
    /// Country uic
    #[serde(rename = "uic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uic: Option<Option<String>>,
}

impl DetailedCountry {
    pub fn new() -> DetailedCountry {
        DetailedCountry {
            name: None,
            settings_name: None,
            iso: None,
            fiscal_iso: None,
            uic: None,
        }
    }
}

