/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.32
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EInvoiceRejectionReason {
    /// E-invoice rejection reason
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
    /// E-invoice status
    #[serde(rename = "ei_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ei_status: Option<Option<String>>,
    /// Error solution.
    #[serde(rename = "solution", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub solution: Option<Option<String>>,
    /// E-invoice rejection error code
    #[serde(rename = "code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub code: Option<Option<String>>,
    /// E-invoice rejection date
    #[serde(rename = "date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date: Option<Option<String>>,
}

impl EInvoiceRejectionReason {
    pub fn new() -> EInvoiceRejectionReason {
        EInvoiceRejectionReason {
            reason: None,
            ei_status: None,
            solution: None,
            code: None,
            date: None,
        }
    }
}

