/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.32
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IssuedDocumentPreCreateInfo {
    /// Issued document numerations
    #[serde(rename = "numerations", skip_serializing_if = "Option::is_none")]
    pub numerations: Option<std::collections::HashMap<String, std::collections::HashMap<String, i32>>>,
    /// Issued document delivery note numerations
    #[serde(rename = "dn_numerations", skip_serializing_if = "Option::is_none")]
    pub dn_numerations: Option<std::collections::HashMap<String, std::collections::HashMap<String, i32>>>,
    #[serde(rename = "default_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_values: Option<Option<Box<models::IssuedDocumentPreCreateInfoDefaultValues>>>,
    #[serde(rename = "extra_data_default_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_data_default_values: Option<Option<Box<models::IssuedDocumentPreCreateInfoExtraDataDefaultValues>>>,
    #[serde(rename = "items_default_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub items_default_values: Option<Option<Box<models::IssuedDocumentPreCreateInfoItemsDefaultValues>>>,
    /// Countries list
    #[serde(rename = "countries_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub countries_list: Option<Option<Vec<String>>>,
    /// Currencies list
    #[serde(rename = "currencies_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub currencies_list: Option<Option<Vec<models::Currency>>>,
    /// Document templates list
    #[serde(rename = "templates_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub templates_list: Option<Option<Vec<models::DocumentTemplate>>>,
    /// Delivery note templates list
    #[serde(rename = "dn_templates_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dn_templates_list: Option<Option<Vec<models::DocumentTemplate>>>,
    /// Accompanying invoice templates list
    #[serde(rename = "ai_templates_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ai_templates_list: Option<Option<Vec<models::DocumentTemplate>>>,
    /// Payment methods list
    #[serde(rename = "payment_methods_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_methods_list: Option<Option<Vec<models::PaymentMethod>>>,
    /// Payment accounts list
    #[serde(rename = "payment_accounts_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub payment_accounts_list: Option<Option<Vec<models::PaymentAccount>>>,
    /// Vat types list
    #[serde(rename = "vat_types_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vat_types_list: Option<Option<Vec<models::VatType>>>,
    /// Languages list
    #[serde(rename = "languages_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub languages_list: Option<Option<Vec<models::Language>>>,
}

impl IssuedDocumentPreCreateInfo {
    pub fn new() -> IssuedDocumentPreCreateInfo {
        IssuedDocumentPreCreateInfo {
            numerations: None,
            dn_numerations: None,
            default_values: None,
            extra_data_default_values: None,
            items_default_values: None,
            countries_list: None,
            currencies_list: None,
            templates_list: None,
            dn_templates_list: None,
            ai_templates_list: None,
            payment_methods_list: None,
            payment_accounts_list: None,
            vat_types_list: None,
            languages_list: None,
        }
    }
}

