/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Language1 {
    /// Language code
    #[serde(rename = "code")]
    pub code: String,
    /// Language extended name
    #[serde(rename = "name")]
    pub name: String,
}

impl Language1 {
    pub fn new(code: String, name: String) -> Language1 {
        Language1 {
            code,
            name,
        }
    }
}

