/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

/// ModifyIssuedDocumentRequest : 



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModifyIssuedDocumentRequest {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<crate::models::IssuedDocument1>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Box<crate::models::IssuedDocumentOptions>>,
}

impl ModifyIssuedDocumentRequest {
    /// 
    pub fn new() -> ModifyIssuedDocumentRequest {
        ModifyIssuedDocumentRequest {
            data: None,
            options: None,
        }
    }
}


