/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonthlyTotal {
    /// Monthly total net amount
    #[serde(rename = "net", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub net: Option<Option<f32>>,
    /// Monthly total gross amount
    #[serde(rename = "gross", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gross: Option<Option<f32>>,
    /// Monthly total receipt number
    #[serde(rename = "count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub count: Option<Option<f32>>,
}

impl MonthlyTotal {
    pub fn new() -> MonthlyTotal {
        MonthlyTotal {
            net: None,
            gross: None,
            count: None,
        }
    }
}


