/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.29
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceivedDocument1 {
    /// Received document id
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Received document type
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "entity")]
    pub entity: Box<crate::models::Entity2>,
    /// Received document date [defaults to today's date]
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Received document category
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<String>>,
    /// Received document description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Received document total net amount
    #[serde(rename = "amount_net", skip_serializing_if = "Option::is_none")]
    pub amount_net: Option<f32>,
    /// Received document total vat amount
    #[serde(rename = "amount_vat", skip_serializing_if = "Option::is_none")]
    pub amount_vat: Option<f32>,
    /// Received document withholding tax amount
    #[serde(rename = "amount_withholding_tax", skip_serializing_if = "Option::is_none")]
    pub amount_withholding_tax: Option<f32>,
    /// Received document other withholding tax amount
    #[serde(rename = "amount_other_withholding_tax", skip_serializing_if = "Option::is_none")]
    pub amount_other_withholding_tax: Option<f32>,
    /// [Read Only] Received document total gross amount
    #[serde(rename = "amount_gross", skip_serializing_if = "Option::is_none")]
    pub amount_gross: Option<f32>,
    /// Received document amortization value
    #[serde(rename = "amortization", skip_serializing_if = "Option::is_none")]
    pub amortization: Option<f32>,
    /// Received document revenue center
    #[serde(rename = "rc_center", skip_serializing_if = "Option::is_none")]
    pub rc_center: Option<String>,
    /// Received document invoice number
    #[serde(rename = "invoice_number", skip_serializing_if = "Option::is_none")]
    pub invoice_number: Option<String>,
    /// Received document is marked
    #[serde(rename = "is_marked", skip_serializing_if = "Option::is_none")]
    pub is_marked: Option<bool>,
    /// Received document has items
    #[serde(rename = "is_detailed", skip_serializing_if = "Option::is_none")]
    pub is_detailed: Option<bool>,
    /// [Read Only] Received document is an e-invoice
    #[serde(rename = "e_invoice", skip_serializing_if = "Option::is_none")]
    pub e_invoice: Option<bool>,
    /// [Read Only] Received document date of the next not paid payment
    #[serde(rename = "next_due_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next_due_date: Option<Option<String>>,
    #[serde(rename = "currency", skip_serializing_if = "Option::is_none")]
    pub currency: Option<Box<crate::models::Currency1>>,
    /// Received document tax deducibility percentage
    #[serde(rename = "tax_deductibility", skip_serializing_if = "Option::is_none")]
    pub tax_deductibility: Option<f32>,
    /// Received document vat deducibility percentage
    #[serde(rename = "vat_deductibility", skip_serializing_if = "Option::is_none")]
    pub vat_deductibility: Option<f32>,
    #[serde(rename = "items_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub items_list: Option<Option<Vec<crate::models::ReceivedDocumentItemsListItem>>>,
    #[serde(rename = "payments_list", skip_serializing_if = "Option::is_none")]
    pub payments_list: Option<Vec<crate::models::ReceivedDocumentPaymentsListItem>>,
    /// [Temporary] [Read Only] Received document url of the attached file
    #[serde(rename = "attachment_url", skip_serializing_if = "Option::is_none")]
    pub attachment_url: Option<String>,
    /// [Temporary] [Read Only] Received document url of the attachment preview
    #[serde(rename = "attachment_preview_url", skip_serializing_if = "Option::is_none")]
    pub attachment_preview_url: Option<String>,
    /// Received document total items amount and total payments amount can differ if this field is set to false
    #[serde(rename = "auto_calculate", skip_serializing_if = "Option::is_none")]
    pub auto_calculate: Option<bool>,
    /// [Write Only] Received document attachment token returned by POST /received_documents/attachment
    #[serde(rename = "attachment_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachment_token: Option<Option<String>>,
    /// Received document creation date
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Received document last update date
    #[serde(rename = "updated_at", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ReceivedDocument1 {
    pub fn new(entity: crate::models::Entity2) -> ReceivedDocument1 {
        ReceivedDocument1 {
            id: None,
            r#type: None,
            entity: Box::new(entity),
            date: None,
            category: None,
            description: None,
            amount_net: None,
            amount_vat: None,
            amount_withholding_tax: None,
            amount_other_withholding_tax: None,
            amount_gross: None,
            amortization: None,
            rc_center: None,
            invoice_number: None,
            is_marked: None,
            is_detailed: None,
            e_invoice: None,
            next_due_date: None,
            currency: None,
            tax_deductibility: None,
            vat_deductibility: None,
            items_list: None,
            payments_list: None,
            attachment_url: None,
            attachment_preview_url: None,
            auto_calculate: None,
            attachment_token: None,
            created_at: None,
            updated_at: None,
        }
    }
}

/// Received document type
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "expense")]
    Expense,
    #[serde(rename = "passive_credit_note")]
    PassiveCreditNote,
    #[serde(rename = "passive_delivery_note")]
    PassiveDeliveryNote,
}

impl Default for Type {
    fn default() -> Type {
        Self::Expense
    }
}

