/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VatType {
    /// Vat type id
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    /// [Read Only] Vat type percentual value
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<f64>>,
    /// Vat type short description
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    /// Vat type notes shown in documents
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    /// Vat type is usable for e-invoices
    #[serde(rename = "e_invoice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub e_invoice: Option<Option<bool>>,
    /// Vat type e-invoice type (natura)
    #[serde(rename = "ei_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ei_type: Option<Option<String>>,
    /// Vat type e-invoice description
    #[serde(rename = "ei_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ei_description: Option<Option<String>>,
    /// [Read Only] Is the vat type is editable.
    #[serde(rename = "editable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub editable: Option<Option<bool>>,
    /// Is the vat type disabled
    #[serde(rename = "is_disabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_disabled: Option<Option<bool>>,
}

impl VatType {
    pub fn new() -> VatType {
        VatType {
            id: None,
            value: None,
            description: None,
            notes: None,
            e_invoice: None,
            ei_type: None,
            ei_description: None,
            editable: None,
            is_disabled: None,
        }
    }
}

