/*
 * Fatture in Cloud API v2 - API Reference
 *
 * Connect your software with Fatture in Cloud, the invoicing platform chosen by more than 500.000 businesses in Italy.   The Fatture in Cloud API is based on REST, and makes possible to interact with the user related data prior authorization via OAuth2 protocol.
 *
 * The version of the OpenAPI document: 2.0.33
 * Contact: info@fattureincloud.it
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEInvoiceXmlErrorResponse {
    #[serde(rename = "error", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error: Option<Option<Box<models::VerifyEInvoiceXmlErrorResponseError>>>,
    #[serde(rename = "extra", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra: Option<Option<Box<models::VerifyEInvoiceXmlErrorResponseExtra>>>,
}

impl VerifyEInvoiceXmlErrorResponse {
    pub fn new() -> VerifyEInvoiceXmlErrorResponse {
        VerifyEInvoiceXmlErrorResponse {
            error: None,
            extra: None,
        }
    }
}

