name: Generate Rust SDK
on: [workflow_dispatch]

jobs:
  generate-rust-sdk:
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout repo
        uses: actions/checkout@v3

      - id: generate-client
        name: Generate Rust Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: rust
          openapi-url: https://github.com/fattureincloud/openapi-fattureincloud/raw/master/openapi-enriched.yaml
          config-file: openapi-config.json
