name: Publish SDK Crate

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [closed]
  ##push:
  ##  branches: [ master ]
  ##  paths:
  ##        - 'rust-client/**'

jobs:
    publish-crate:
        if: ${{ github.event.pull_request.merged }}
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
             - uses: actions/checkout@v4
             - uses: dtolnay/rust-toolchain@stable
             - uses: katyo/publish-crates@v2
               with:
                    path: './rust-client'
                    ignore-unpublished-changes: true
                    registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
