name: Publish SDK Crate

on:
  workflow_dispatch:
  ##push:
  ##  branches: [ master ]
  ##  paths:
  ##        - 'rust-client/**'

jobs:
    publish-crate:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
             - uses: actions/checkout@v4
             - uses: actions-rs/toolchain@v1
               with:
                   toolchain: stable
                   override: true
             - uses: katyo/publish-crates@v2
               with:
                    path: './rust-client'
                    ignore-unpublished-changes: true
                    dry-run: true
                    registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
